DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS comment;

CREATE TABLE post (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT UNIQUE NOT NULL,
	body TEXT NOT NULL
);

CREATE TABLE comment (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	post_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	body TEXT NOT NULL,
	FOREIGN KEY (post_id) REFERENCES post (id)
);